/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;
import proyecto.pkg1.Listas;

/**
 *
 * @author Kevin
 */
public class VentanaAgregarPlato extends javax.swing.JFrame {

    Listas listas;
    String menu;
    VentanaOtroPlato otroPlato;

    /**
     * Creates new form VentanaAgregarPlato
     *
     * @param listas
     */
    public VentanaAgregarPlato(Listas listas) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.otroPlato = new VentanaOtroPlato(this);
        this.listas = listas;
        this.menu = "";

        String[] restaurantes = listas.getListaRestaurantes().getArrayRest();
        for (int i = 0; i < restaurantes.length; i++) {
            restaurante.addItem(restaurantes[i]);
        }

    }

    public void comunicacion(String plato) {

        this.menu += plato + "/";
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        restaurante = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        agregarPlato = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        terminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        restaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restauranteActionPerformed(evt);
            }
        });
        jPanel1.add(restaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 120, -1));

        jLabel2.setText("Seleccione el restaurante: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        agregarPlato.setText("Agregar plato");
        agregarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPlatoActionPerformed(evt);
            }
        });
        jPanel1.add(agregarPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        terminar.setText("Terminar");
        terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarActionPerformed(evt);
            }
        });
        jPanel1.add(terminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restauranteActionPerformed

    }//GEN-LAST:event_restauranteActionPerformed

    private void agregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPlatoActionPerformed
        otroPlato.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_agregarPlatoActionPerformed

    private void terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarActionPerformed
        try {
            listas.getListaRestaurantes().setMenus(restaurante.getSelectedItem().toString(), menu);
            JOptionPane.showMessageDialog(null, "Se agregó correctamente");
            new VentanaAdmin(listas).setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error al agregar");
        }
         JOptionPane.showMessageDialog(null, listas.getListaRestaurantes().getInformacionLista());
    }//GEN-LAST:event_terminarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        new VentanaAdmin(listas).setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPlato;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> restaurante;
    private javax.swing.JButton terminar;
    // End of variables declaration//GEN-END:variables
}
