/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;
import proyecto.pkg1.Funciones;
import proyecto.pkg1.Listas;

/**
 *
 * @author Kevin
 */
public class VentanaNuevoLocal extends javax.swing.JFrame {

    Listas listas;
    String menu;
    VentanaOtroPlato otroPlato;
    Funciones f;

    /**
     * Creates new form VentanaNuevoLocal
     */
    public VentanaNuevoLocal(Listas listas) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listas = listas;
        this.otroPlato = new VentanaOtroPlato(this);
        this.f = new Funciones();
        this.menu = "";

        char[] direcciones = f.getDirecciones(listas);

        for (int i = 0; i < direcciones.length; i++) {
            entrada.addItem(String.valueOf(direcciones[i]));
            salida.addItem(String.valueOf(direcciones[i]));
        }

    }

    public void comunicacion(String plato) {

        this.menu += plato + "/";
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        entrada = new javax.swing.JComboBox<>();
        pesoEntrada = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salida = new javax.swing.JComboBox<>();
        pesoSalida = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        agregarPlato = new javax.swing.JButton();
        agregarLocal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Seleccione una direccion de entrada: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jLabel8.setText("Distancia:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        jPanel1.add(entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 190, -1));

        pesoEntrada.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(pesoEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 70, -1));

        jLabel5.setText("Seleccione una direccion de salida: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel7.setText("Distancia:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jPanel1.add(salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 190, -1));

        pesoSalida.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(pesoSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 70, -1));

        jLabel1.setText("Dirección:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 200, -1));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, -1));

        jLabel2.setText("Nombre del nuevo local: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        agregarPlato.setText("Agregar plato");
        agregarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPlatoActionPerformed(evt);
            }
        });
        jPanel1.add(agregarPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        agregarLocal.setText("Agregar local");
        agregarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarLocalActionPerformed(evt);
            }
        });
        jPanel1.add(agregarLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPlatoActionPerformed
        otroPlato.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_agregarPlatoActionPerformed

    private void agregarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarLocalActionPerformed
        try {
            if (!nombre.getText().isBlank() && !direccion.getText().isBlank() && !menu.isBlank() && f.validaDireccionRest(direccion.getText())) {
                String menu_str = menu.substring(0, menu.length() - 1);
                if (!entrada.getSelectedItem().toString().equals(salida.getSelectedItem().toString())) {
                    if (!listas.getListaRestaurantes().existeDireccion(direccion.getText())) {
                        listas.getListaRestaurantes().agregarFinal(direccion.getText().charAt(0), nombre.getText(), menu_str.split("/"));
                        listas.getListaRutas().agregarFinal(entrada.getSelectedItem().toString().charAt(0), direccion.getText().toUpperCase().charAt(0), Integer.parseInt(pesoEntrada.getValue().toString()));
                        listas.getListaRutas().agregarFinal(direccion.getText().charAt(0), salida.getSelectedItem().toString().charAt(0), Integer.parseInt(pesoSalida.getValue().toString()));
                        JOptionPane.showMessageDialog(null, "El local fue agregado correctamente");
                        new VentanaAdmin(listas).setVisible(true);
                        dispose();

                    }else{
                        JOptionPane.showMessageDialog(null, "La dirección ya existe. Por favor, ingrese otra.");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "La dirección de entrada y salida no pueden coincidir.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor, complete los campos correctamente.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo agregar el local, complete los campos correctamente.");
        }
    }//GEN-LAST:event_agregarLocalActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        new VentanaAdmin(listas).setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarLocal;
    private javax.swing.JButton agregarPlato;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField direccion;
    private javax.swing.JComboBox<String> entrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JSpinner pesoEntrada;
    private javax.swing.JSpinner pesoSalida;
    private javax.swing.JComboBox<String> salida;
    // End of variables declaration//GEN-END:variables
}
