/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;
import proyecto.pkg1.Listas;

/**
 *
 * @author Kevin
 */
public class VentanaEliminarPlato extends javax.swing.JFrame {

    Listas listas;

    /**
     * Creates new form VentanaEliminarPlatos
     */
    public VentanaEliminarPlato(Listas listas) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listas = listas;
        String[] restaurantes = listas.getListaRestaurantes().getArrayRest();
        for (int i = 0; i < restaurantes.length; i++) {
            restaurante.addItem(restaurantes[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        restaurante = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        plato = new javax.swing.JComboBox<>();
        eliminarPlato = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Seleccione el restaurante: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        restaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restauranteActionPerformed(evt);
            }
        });
        jPanel1.add(restaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 120, -1));

        jLabel1.setText("Seleccione plato a eliminar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jPanel1.add(plato, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 120, -1));

        eliminarPlato.setText("Eliminar plato");
        eliminarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPlatoActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restauranteActionPerformed
        String[] menu = listas.getListaRestaurantes().buscarRest(String.valueOf(restaurante.getSelectedItem()));

        try {
            plato.removeAllItems();
            for (int i = 0; i < menu.length; i++) {
                plato.addItem(menu[i]);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_restauranteActionPerformed

    private void eliminarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPlatoActionPerformed
        try {
            listas.getListaRestaurantes().EliminarPlato(String.valueOf(restaurante.getSelectedItem()), String.valueOf(plato.getSelectedItem()));
            JOptionPane.showMessageDialog(null, "Se eliminó correctamente");
            new VentanaAdmin(listas).setVisible(true);
            dispose();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ocurrió un error.");
        }
        JOptionPane.showMessageDialog(null, listas.getListaRestaurantes().getInformacionLista());
    }//GEN-LAST:event_eliminarPlatoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        new VentanaAdmin(listas).setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton eliminarPlato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> plato;
    private javax.swing.JComboBox<String> restaurante;
    // End of variables declaration//GEN-END:variables
}
