/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import proyecto.pkg1.Dijkstra;
import proyecto.pkg1.ListaDirecciones;
import proyecto.pkg1.Listas;
import proyecto.pkg1.MatrizAdyacencia;

/**
 *
 * @author Kevin
 */
public class VentanaDriver extends javax.swing.JFrame {

    Listas listas;
    MatrizAdyacencia matrizAdy;
    Dijkstra dk;
    ListaDirecciones ld;

    /**
     * Creates new form VentanaDriver
     *
     * @param listas
     */
    public VentanaDriver(Listas listas) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listas = listas;
        this.ld = listas.getListaDirecciones();
        String[] pedidos = listas.getListaPedidos().getArrayPedidos();

        for (int i = 0; i < pedidos.length; i++) {
            pedido.addItem(pedidos[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pedido = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Dijkstra = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Seleccione un pedido: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 140, -1));

        jPanel1.add(pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 450, -1));

        jLabel2.setText("Seleccione el algoritmo por el cual desea saber la ruta de envío:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 390, -1));

        Dijkstra.setText(" Dijkstra");
        Dijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DijkstraActionPerformed(evt);
            }
        });
        jPanel1.add(Dijkstra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 120, -1));

        jButton2.setText("Floyd-Warshall");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, -1));

        jButton3.setText("Volver al menú");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 360));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new VentanaRolUsuario(listas).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DijkstraActionPerformed
        String seleccionado = pedido.getSelectedItem().toString();
        char origen = seleccionado.charAt(0);
        char destino = seleccionado.charAt(6);
        
        System.out.println(origen);
        System.out.println(destino);

        matrizAdy = new MatrizAdyacencia(listas.getListaDirecciones().getTamano());
        String[] rutas = listas.getListaRutas().getArrayRutas();
        
        for (int i = 0; i < rutas.length; i++) {

            matrizAdy.agregarVert(ld.getPosicionInt(rutas[i].split(",")[0]), ld.getPosicionInt(rutas[i].split(",")[1]), Integer.parseInt(rutas[i].split(",")[2]));
        }
        int[][] matriz = matrizAdy.getMatriz();

        dk = new Dijkstra();
        dk.Dijkstra(matriz, ld.getPosicionInt(Character.toString(origen)), ld, Character.toString(destino));

    }//GEN-LAST:event_DijkstraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dijkstra;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> pedido;
    // End of variables declaration//GEN-END:variables
}
