/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import proyecto.pkg1.Listas;

/**
 *
 * @author Kevin
 */
public class VentanaNuevoLocal extends javax.swing.JFrame {

    Listas listas;
    String menu;
    VentanaOtroPlato otroPlato;

    /**
     * Creates new form VentanaNuevoLocal
     */
    public VentanaNuevoLocal(Listas listas) {
        initComponents();
        this.listas = listas;
    }

    public void comunicacion(String plato) {
        //this.menu += info;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        entrada = new javax.swing.JComboBox<>();
        pesoEntrada = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salida = new javax.swing.JComboBox<>();
        pesoSalida = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        agregarPlato = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Seleccione una direccion de entrada: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jLabel8.setText("Distancia:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        jPanel1.add(entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 190, -1));

        pesoEntrada.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(pesoEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 70, -1));

        jLabel5.setText("Seleccione una direccion de salida: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel7.setText("Distancia:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jPanel1.add(salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 190, -1));

        pesoSalida.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(pesoSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 70, -1));

        jLabel1.setText("Dirección:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 190, -1));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, -1));

        jLabel2.setText("Nombre del nuevo local: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jButton1.setText("Cancelar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        agregarPlato.setText("Agregar plato");
        agregarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPlatoActionPerformed(evt);
            }
        });
        jPanel1.add(agregarPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jButton3.setText("Agregar local");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPlatoActionPerformed

    }//GEN-LAST:event_agregarPlatoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPlato;
    private javax.swing.JComboBox<String> entrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nombre;
    private javax.swing.JSpinner pesoEntrada;
    private javax.swing.JSpinner pesoSalida;
    private javax.swing.JComboBox<String> salida;
    // End of variables declaration//GEN-END:variables
}
