/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class VentanaOtroPlato extends javax.swing.JFrame {

    VentanaNuevoLocal nuevoLocal;
    VentanaAgregarPlato ventanaAgregarPlato;
    int ventana;

    /**
     * Creates new form VentanaOtroPlato
     */
    public VentanaOtroPlato(VentanaNuevoLocal nuevoLocal) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.nuevoLocal = nuevoLocal;
        this.ventana = 1;
    }

    public VentanaOtroPlato(VentanaAgregarPlato ventanaAgregarPlato) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ventanaAgregarPlato = ventanaAgregarPlato;
        this.ventana = 2;
    }

    private void Enviar(String info) {
        if (ventana == 1) {
            nuevoLocal.comunicacion(info);

        } else {
            ventanaAgregarPlato.comunicacion(info);
        }
        plato.setText("");
        dispose();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        plato = new javax.swing.JTextField();
        agregarPlato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese el nombre del plato:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        plato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platoActionPerformed(evt);
            }
        });
        jPanel1.add(plato, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 150, -1));

        agregarPlato.setText("Agregar plato");
        agregarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPlatoActionPerformed(evt);
            }
        });
        jPanel1.add(agregarPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPlatoActionPerformed
        if (!plato.getText().isBlank()) {
            Enviar(plato.getText());
            JOptionPane.showMessageDialog(null, "Plato agregado correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "No puede dejar vacío la casilla");
        }

    }//GEN-LAST:event_agregarPlatoActionPerformed

    private void platoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPlato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField plato;
    // End of variables declaration//GEN-END:variables
}
