/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import proyecto.pkg1.DFS;
import proyecto.pkg1.ListaDirecciones;
import proyecto.pkg1.Listas;
import proyecto.pkg1.MatrizAdyacencia;

/**
 *
 * @author Kevin
 */
public class VentanaRecorrido extends javax.swing.JFrame {

    Listas listas;
    MatrizAdyacencia matrizAdy;
    ListaDirecciones ld;
    DFS recorrido;

    /**
     * Creates new form VentanaRecorrido
     *
     * @param listas
     */
    public VentanaRecorrido(Listas listas) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listas = listas;
        this.ld = listas.getListaDirecciones();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        recorridoDFS = new javax.swing.JToggleButton();
        volver = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recorridoDFS.setText("Recorrido DFS");
        recorridoDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recorridoDFSActionPerformed(evt);
            }
        });
        jPanel1.add(recorridoDFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 140, -1));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        new VentanaGeneral(listas).setVisible(true);
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void recorridoDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recorridoDFSActionPerformed
        matrizAdy = new MatrizAdyacencia(listas.getListaDirecciones().getTamano());
        String[] rutas = listas.getListaRutas().getArrayRutas();

        for (int i = 0; i < rutas.length; i++) {

            matrizAdy.agregarVert(ld.getPosicionInt(rutas[i].split(",")[0]), ld.getPosicionInt(rutas[i].split(",")[1]), Integer.parseInt(rutas[i].split(",")[2]));
        }

        int[][] matriz = matrizAdy.getMatrizSP();
        recorrido = new DFS();
        boolean[] visited = new boolean[matriz.length];
        int count = 0;
        for (int i = 0; i < matriz.length; i++) {
            if (!visited[i]) {
                recorrido.dfs(i, matriz, visited, ld);
                count++;
            }
        }
    }//GEN-LAST:event_recorridoDFSActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton recorridoDFS;
    private javax.swing.JToggleButton volver;
    // End of variables declaration//GEN-END:variables
}
